"""Alembic scaffolding works end-to-end.

We don't run a full migration matrix here (overkill at one revision) — these
tests catch the breakage modes that matter:
  - Initial migration emits the same schema `create_all` produces
  - `stamp head` records the version row without running migrations
  - The CLI commands wire up without crashing on the happy path
"""
from pathlib import Path

import pytest


def test_alembic_files_exist():
    """Sanity: the scaffold is present where the CLI expects it."""
    root = Path(__file__).resolve().parents[1]
    assert (root / "alembic.ini").exists()
    assert (root / "alembic" / "env.py").exists()
    assert (root / "alembic" / "script.py.mako").exists()
    versions = list((root / "alembic" / "versions").glob("*.py"))
    # Exactly one revision for now: the initial schema.
    assert len(versions) >= 1


def test_initial_migration_has_all_five_tables():
    """The autogenerated initial migration must create every ORM table."""
    root = Path(__file__).resolve().parents[1]
    text = ""
    for f in (root / "alembic" / "versions").glob("*initial*.py"):
        text = f.read_text(encoding="utf-8")
        break
    assert text, "no initial migration found"
    for table in ("prompts", "prompt_tags", "models", "runs", "evaluations", "tag_taxonomy"):
        assert f"'{table}'" in text or f'"{table}"' in text, f"table {table} missing"


def test_alembic_config_helper_returns_a_config():
    from lemon_squeeze.cli import _alembic_config
    cfg = _alembic_config()
    # script_location is set programmatically; verify it points at our dir.
    assert "alembic" in cfg.get_main_option("script_location")


def test_alembic_revision_matches_metadata(tmp_path):
    """End-to-end: stamping a fresh DB and inspecting the schema matches ORM.

    env.py always picks up `settings.db_url`, so we redirect settings at the
    temp DB and let everything route through that.
    """
    from alembic.runtime.migration import MigrationContext
    from sqlalchemy import create_engine

    from lemon_squeeze.cli import _alembic_config
    from lemon_squeeze.config import settings
    from lemon_squeeze.db import Base

    db = tmp_path / "alembic_test.db"
    saved_db_path = settings.db_path
    settings.db_path = db
    try:
        engine = create_engine(f"sqlite:///{db}", future=True)
        Base.metadata.create_all(engine)

        from alembic import command
        cfg = _alembic_config()
        command.stamp(cfg, "head")

        with engine.connect() as conn:
            ctx = MigrationContext.configure(conn)
            current = ctx.get_current_revision()
        assert current is not None
        assert len(current) == 12  # 12 hex chars
    finally:
        settings.db_path = saved_db_path
