"""initial_schema

Revision ID: dd2bf37a86ee
Revises: 
Create Date: 2026-06-07 17:03:34.992046
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd2bf37a86ee'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('family', sa.String(length=64), nullable=True),
    sa.Column('size_params_b', sa.Float(), nullable=True),
    sa.Column('context_window', sa.Integer(), nullable=True),
    sa.Column('local', sa.Boolean(), nullable=False),
    sa.Column('cost_in_per_mtok', sa.Float(), nullable=True),
    sa.Column('cost_out_per_mtok', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_models_name'), ['name'], unique=True)

    op.create_table('prompts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_ref', sa.String(length=512), nullable=True),
    sa.Column('source_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', lemon_squeeze.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', lemon_squeeze.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompts_content_hash'), ['content_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_prompts_source'), ['source'], unique=False)
        batch_op.create_index('ix_prompts_source_created', ['source', 'created_at'], unique=False)

    op.create_table('tag_taxonomy',
    sa.Column('tag', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['parent'], ['tag_taxonomy.tag'], ),
    sa.PrimaryKeyConstraint('tag')
    )
    op.create_table('prompt_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt_id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=64), nullable=False),
    sa.Column('classifier', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', lemon_squeeze.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prompt_id', 'tag', 'classifier', name='uq_prompt_tag_classifier')
    )
    with op.batch_alter_table('prompt_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompt_tags_prompt_id'), ['prompt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompt_tags_tag'), ['tag'], unique=False)

    op.create_table('runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('top_p', sa.Float(), nullable=True),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('run_metadata', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', lemon_squeeze.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_runs_model_id'), ['model_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_runs_prompt_id'), ['prompt_id'], unique=False)

    op.create_table('evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('rubric', sa.String(length=64), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('scored_by', sa.String(length=32), nullable=False),
    sa.Column('judge_model', sa.String(length=128), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('eval_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', lemon_squeeze.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluations_rubric'), ['rubric'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluations_run_id'), ['run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluations_run_id'))
        batch_op.drop_index(batch_op.f('ix_evaluations_rubric'))

    op.drop_table('evaluations')
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runs_prompt_id'))
        batch_op.drop_index(batch_op.f('ix_runs_model_id'))

    op.drop_table('runs')
    with op.batch_alter_table('prompt_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompt_tags_tag'))
        batch_op.drop_index(batch_op.f('ix_prompt_tags_prompt_id'))

    op.drop_table('prompt_tags')
    op.drop_table('tag_taxonomy')
    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.drop_index('ix_prompts_source_created')
        batch_op.drop_index(batch_op.f('ix_prompts_source'))
        batch_op.drop_index(batch_op.f('ix_prompts_content_hash'))

    op.drop_table('prompts')
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_models_name'))

    op.drop_table('models')
    # ### end Alembic commands ###
